name: ci

on:
  pull_request:
    branches: [main, beta, rc]
    paths-ignore:
      - '**.md'
  push:
    branches: [main, beta, rc]
    paths-ignore:
      - '**.md'

env:
  coveralls_branch: main
  coveralls_node: current
  coveralls_runner: ubuntu-latest

jobs:
  blt:
    name: BLT
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
          - 16
          - 18
          - lts/*
          - current
        runner:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run test
      - if: ${{ env.coveralls_branch == github.ref_name && env.coveralls_node == matrix.node && env.coveralls_runner == matrix.runner }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
